export const membersData = {
  aanush: {
    name: "Aanush Kumar",
    age: "15",
    dob: "20/09/07",
    height: "5'7",
    weight: "62kg",
    favoriteArtist: "Arctic Monkeys",
    favoriteSong: "Here With Me by D4vid",
    favoriteSongUrl:
      "https://open.spotify.com/track/5LrN7yUQAzvthd4QujgPFr?si=2878935ad4b244df",
    favoriteWord: "Jhattu",
    favoriteSongEmbed:
      "https://open.spotify.com/embed/track/5LrN7yUQAzvthd4QujgPFr?utm_source=generator",
    favoriteColor: "Prussian Blue",
    playlistUrl: "https://spotify.link/pI0bzpYh3Cb",
    imageUrl: "/assets/Aanush.jpg",
    description: "I Love Shreya.",
    instagram: "https://instagram.com/aanushkr",
    location: "Savusavu, Fiji",
    hobbies: ["Soccer", "Loving Shreya Kirpal"],
    interests: ["Shreya Kirpal"],
    roles: ["Shreya Luvr", "Shahaan's Mommy"],
    link: "/members/aanush",
    gif: "https://media.giphy.com/media/3o85xJohCZUc524lSU/giphy.gif",
  },
  shahaan: {
    name: "Mohammad Shahaan",
    age: "16",
    dob: "16/08/07",
    height: "5'8ft",
    weight: "79kg",
    favoriteArtist: "Drake",
    favoriteSong: "505 by Arctic Monkeys",
    favoriteSongUrl:
      "https://open.spotify.com/track/0BxE4FqsDD1Ot4YuBXwAPp?si=40eb02c7a8114823",
    favoriteWord: "Propaganda",
    favoriteColor: "Blue",
    playlistUrl:
      "https://open.spotify.com/playlist/66LFf9vnnMOdkHTQLwvB0Y?si=508ef656eb84407c",
    favoriteSongEmbed:
      "https://open.spotify.com/embed/track/0BxE4FqsDD1Ot4YuBXwAPp?utm_source=generator",
    imageUrl: "/assets/Shahaan.jpg",
    description: "Funny irl but not online.",
    instagram: "https://instagram.com/shqhqqn",
    location: "Suva, Fiji",
    hobbies: ["Gaming", "Harassment"],
    interests: [],
    roles: ["OVO"],
    link: "/members/shahaan",
    gif: "https://cdn.discordapp.com/attachments/993789383868162098/1150395008659234846/giphy.gif",
  },
  nikhil: {
    name: "Nikhil Aryan Naiker",
    age: "17",
    height: "5'7ft",
    weight: "83kg",
    favoriteArtist: "The Weeknd",
    favoriteSong: "Wicked Games",
    favoriteSongUrl:
      "https://open.spotify.com/track/00aqkszH1FdUiJJWvX6iEl?si=003f57fbf2fb4ecb",
    favoriteSongEmbed:
      "https://open.spotify.com/embed/track/00aqkszH1FdUiJJWvX6iEl?utm_source=generator",
    favoriteWord: "XO",
    favoriteColor: "Black",
    playlistUrl:
      "https://open.spotify.com/playlist/6TrcN8ZyCUJCzORfmc0gZ0?si=6f8d4b515e6d4b84",
    imageUrl: "/assets/Nikhil.jpg",
    description: "Waking up is the second hardest thing in the morning.",
    instagram: "https://instagram.com/fr3sh.budusy",
    location: "Suva, Fiji",
    hobbies: ["The Weeknd", "Brawlhalla", "Deadlifting"],
    interests: ["Powerlifting", "Coding"],
    roles: ["XO", "Racist", "Batman", "She/Him"],
    link: "/members/nikhil",
    gif: "https://media.giphy.com/media/i7qODl4xzhcPPGf8Do/giphy.gif",
  },
  waji: {
    name: "Wajahat Munshi (Waji)",
    age: "15",
    dob: "08/03/08",
    height: "175cm",
    weight: "74kg",
    favoriteArtist: "Baby Keem",
    favoriteSong: "16 by Baby Keem",
    favoriteSongUrl:
      "https://open.spotify.com/track/1Is8hGpkGMiePASAxBluxM?si=f859d29a7cfc435d",
    favoriteSongEmbed:
      "https://open.spotify.com/embed/track/1Is8hGpkGMiePASAxBluxM?utm_source=generator",
    favoriteWord: "starts with the letter n",
    favoriteColor: "Green",
    playlistUrl: "https://spotify.link/xRhavsetYCb",
    imageUrl: "/assets/Waji.jpg",
    description: "Ejaculate and Evacuate.",
    instagram: "https://instagram.com/wxjixz",
    location: "Suva, Fiji",
    hobbies: ["weightlifting ", "Sobbing "],
    interests: ["You"],
    roles: ["Lord and Savior", "Dig Bick", "xoxokwaiboyuwu327"],
    link: "/members/waji",
    gif: "https://media.giphy.com/media/4QPaVH07ErzOk8jK9B/giphy.gif",
  },
  shane: {
    name: "Sharad Shane Jagrup ",
    age: "18",
    dob: "02/08/05",
    height: "5'7 ft",
    weight: "70kg",
    favoriteArtist: "The Neighborhood ",
    favoriteSong: "Secret Door by Arctic Monkeys",
    favoriteSongUrl:
      "https://open.spotify.com/track/4dtP86vkhzwNXCFpCtizce?si=d14a64ec9aa445f2",
    favoriteSongEmbed:
      "https://open.spotify.com/embed/track/4dtP86vkhzwNXCFpCtizce?utm_source=generator",
    favoriteWord: "acha bhai ",
    favoriteColor: "Black",
    playlistUrl: "https://open.spotify.com/playlist/22UzQUqngjGBQnCS1INF27",
    imageUrl: "/assets/Shane.jpg",
    description:
      "I have a very low self esteem & I love my gf she is the coolest ",
    instagram: "https://instagram.com/xviishane",
    location: "Suva, Fiji",
    hobbies: ["Football", "Gym"],
    interests: ["Anime", "Reading"],
    roles: ["Something", "Pedophile", "Alcoholic"],
    link: "/members/shane",
    gif: "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExbmJzdGd1aGR0ZHp0Z2hyZDBkdGdyam5oZjBlN3FxeDk2dHY1ZGQzcSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/cOSbH8NoUFt9MXbuie/giphy.gif",
  },

  riddhi: {
    name: "Riddhi Bharat",
    age: "13",
    dob: "15/06/10",
    height: "4'10.5 ft",
    weight: "49kg",
    favoriteArtist: "Daniel Ceaser",
    favoriteSong: "Hold me down by Daniel Ceaser",
    favoriteSongUrl:
      "https://open.spotify.com/track/1Mza2sr6tPhy6jjI3HB9fW?si=3314b8bd5e2048df",
    favoriteSongEmbed:
      "https://open.spotify.com/embed/track/1Mza2sr6tPhy6jjI3HB9fW?utm_source=generator",
    favoriteWord: "Looooond",
    favoriteColor: "Lavender",
    playlistUrl:
      "https://open.spotify.com/playlist/7jwg7cbtufMVkOeyp9ZjzK?si=3a2kqUttQ8CBa6CLsTxiqA",
    imageUrl: "/assets/Riddhi.jpg",
    description:
      "I am the tallest person in nonchalant (im built like a dwarf) ",
    instagram: "https://instagram.com/rid2kool",
    location: "Suva, Fiji",
    hobbies: ["Reading", "Baking"],
    interests: ["Being a spectator in sports"],
    roles: ["Everything"],
    link: "/members/riddhi",
    gif: "https://media.giphy.com/media/Red9i0GN54sZW/giphy.gif",
  },
  xzya: {
    name: "Xzya Gagan",
    age: "18",
    dob: "19/05/05",
    height: "6ft",
    weight: "53kg",
    favoriteArtist: "Josh A",
    favoriteSong: "Heartbreaks by Josh A",
    favoriteSongUrl:
      "https://open.spotify.com/track/1AjJhhtf6JR3wanmu48lAM?si=e1a3be0d70644904",
    favoriteSongEmbed:
      "https://open.spotify.com/embed/track/1AjJhhtf6JR3wanmu48lAM?utm_source=generator",
    favoriteWord: "F**k",
    favoriteColor: "Black (it's a shade)",
    playlistUrl:
      "https://open.spotify.com/playlist/447RClBuLe7q1B0HhHx3HC?si=d708b56f450c4458",
    imageUrl: "/assets/Xzya.jpg",
    description:
      "I am a counselor for shane and pretty much chilling. I got a lovely gf n i hate school",
    instagram: "https://instagram.com/Priv_xzya",
    location: "Savusavu, Fiji",
    hobbies: ["Games", "Chill Sessions", "Rough ***"],
    interests: [
      "Preventing the universe from collapsing (checking up on the boys)",
    ],
    roles: ["God"],
    link: "/members/xzya",
    gif: "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExdjc2cjkyNjFmM2t4d2QzeHdhaDRyc3lidWo5NzdlNHA2OGVzZTdwNyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/gFPxNhzEWdFCCRAqf0/giphy.gif",
  },
  arav: {
    name: "Arav Deo",
    age: "14",
    dob: "20/10/08",
    height: "5'7 ft",
    weight: "55kg",
    favoriteArtist: "Leo Messi",
    favoriteSong: "Chaleya by Arjit Singh",
    favoriteSongUrl:
      "https://open.spotify.com/track/3xMHXmedL5Rvfxmiar9Ryv?si=8013ac9294b344bf",
    favoriteSongEmbed:
      "https://open.spotify.com/embed/track/3xMHXmedL5Rvfxmiar9Ryv?utm_source=generator",
    favoriteWord: "Dovicai",
    favoriteColor: "Black",
    playlistUrl: "",
    imageUrl: "/assets/Arav.jpg",
    description: "Coming Soon...",
    instagram: "https://instagram.com/aravdeo108",
    location: "Suva, Fiji",
    hobbies: ["Games", "Soccer"],
    interests: ["Software", "Soccer"],
    roles: ["-"],
    link: "/members/arav",
    gif: "https://media.giphy.com/media/3osxYyPu7mA7ySNBgQ/giphy.gif",
  },
  ethan: {
    name: "Ethan Ram",
    age: "15",
    dob: "22/10/07",
    height: "5'3ft",
    weight: "50kg",
    favoriteArtist: "Clairo",
    favoriteSong: "Amoeba by Clairo",
    favoriteSongUrl:
      "https://open.spotify.com/track/0HAqq2GcQKyi3s87GuN7jU?si=dab0b473da71446b",
    favoriteSongEmbed:
      "https://open.spotify.com/embed/track/0HAqq2GcQKyi3s87GuN7jU?utm_source=generator",
    favoriteWord: "bro",
    favoriteColor: "Blue",
    playlistUrl: "",
    imageUrl: "/assets/Ethan.jpg",
    description: "best cm in the world irl and in fifa ",
    instagram: "https://instagram.com/3thqnexe",
    location: "California, US ",
    hobbies: ["Football", "Gaming"],
    interests: ["Journalism", "Photography"],
    roles: ["Comedic Relief"],
    link: "/members/ethan",
    gif: "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExMDF1bDM3NXlsbDJ2OTJoa3N2Z2szOTFqem9rMnFhb3o4MDIyNW5xeiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/xT1XH3TrY1zAEKgrQs/giphy.gif",
  },
  plavana: {
    name: "Plavana Singh",
    age: "15",
    dob: "26/11/07",
    height: "6'7 ft",
    weight: "69kg",
    favoriteArtist: "Taylor Swift",
    favoriteSong: "Style by Taylor Swift",
    favoriteSongUrl:
      "https://open.spotify.com/track/0ug5NqcwcFR2xrfTkc7k8e?si=a17e633be6d14620",
    favoriteSongEmbed:
      "https://open.spotify.com/track/0ug5NqcwcFR2xrfTkc7k8e?si=a17e633be6d14620",
    favoriteWord: "F**k",
    favoriteColor: "Yellowish Green",
    playlistUrl: "",
    imageUrl: "/assets/Plavana.jpg",
    description:
      "Stubborn, Short girl with brains, Pretty, Crybaby,Good fashion sense.",
    instagram: "https://instagram.com/opacaro.phile.08",
    location: "Suva, Fiji",
    hobbies: ["None"],
    interests: ["I have none"],
    roles: ["None of ur business"],
    link: "/members/plavana",
    gif: "https://media.giphy.com/media/jO2B3Llymxny6BSObJ/giphy.gif",
  },
  josh: {
    name: "Josh Daniel",
    age: "15",
    dob: "10/01/08",
    height: "5'7 ft",
    weight: "67kg",
    favoriteArtist: "Drake",
    favoriteSong: "5am in Toronto by Drake",
    favoriteSongUrl:
      "https://open.spotify.com/track/0FnxK9FEAQyPJ284QcieNb?si=af9113997f08402b",
    favoriteSongEmbed:
      "https://open.spotify.com/embed/track/0FnxK9FEAQyPJ284QcieNb?utm_source=generator",
    favoriteWord: "Nigeria",
    favoriteColor: "Purple",
    playlistUrl:
      "https://open.spotify.com/playlist/4hfMkBFUEDdz7jNjjGOSHx?si=4Bq6CrktQf6pUlivPrnoVw",
    imageUrl: "/assets/Josh.jpg",
    description: "Lazy dumb big forehead and cakobau",
    instagram: "https://www.instagram.com/beadybrag",
    location: "Lami, Fiji",
    hobbies: ["loser😔"],
    interests: ["Footy", "Anime"],
    roles: ["Member"],
    link: "/members/josh",
    gif: "https://media.giphy.com/media/1zgzISaYrnMAYRJJEr/giphy.gif",
  },
  dharav: {
    name: "Dharav Kapadia",
    age: "15",
    dob: "13/11/07",
    height: "6'2 ft",
    weight: "97kg",
    favoriteArtist: "Drake",
    favoriteSong: "Emotionless by Drake",
    favoriteSongUrl:
      "https://open.spotify.com/track/5Psnhdkyanjpgc2P8A5TSM?si=284c0c7979744068",
    favoriteSongEmbed:
      "https://open.spotify.com/embed/track/5Psnhdkyanjpgc2P8A5TSM?utm_source=generator",
    favoriteWord: "Jhatu",
    favoriteColor: "Purple",
    playlistUrl: "https://spotify.link/1XFNBvktYCb",
    imageUrl: "/assets/Dharav.png",
    description: "Top 2 but not no.2",
    instagram: "https://instagram.com/dhxravvv",
    location: "Suva, Fiji",
    hobbies: ["Talking to my gf"],
    interests: [
      "Listening to c.a.s while laying on the ground",
      "Watching the sunset",
    ],
    roles: ["Member"],
    link: "/members/dharav",
    gif: "https://media.giphy.com/media/xT4uQjxPma99QsihhK/giphy.gif",
  },
  nate: {
    name: "Asinate Tuiniceva",
    age: "15",
    dob: "11/02/08",
    height: "5'9.5 ft",
    weight: "60kg",
    favoriteArtist: "The Weeknd",
    favoriteSong: "Coming Down by The Weeknd",
    favoriteSongUrl:
      "https://open.spotify.com/track/3mHO1J6kfiArjBo1zhLFGP?si=a697074ae0d14187",
    favoriteSongEmbed:
      "https://open.spotify.com/embed/track/3mHO1J6kfiArjBo1zhLFGP?utm_source=generator",
    favoriteWord: "Gang",
    favoriteColor: "Purple",
    playlistUrl: "https://spotify.link/1XFNBvktYCb",
    imageUrl: "/assets/Nate.jpg",
    description: "cutie patootie fr (slenderman regen)",
    instagram: "https://instagram.com/nat3yy",
    location: "Suva, Fiji",
    hobbies: ["Badminton", "Cooking"],
    interests: ["History", "Making Money"],
    roles: ["Boci", "Pedopohile"],
    link: "/members/nate",
    gif: "https://media.giphy.com/media/xT4uQjxPma99QsihhK/giphy.gif",
  },
  shreya: {
    name: "Shreya Kirpal",
    age: "16",
    dob: "31/03/07",
    height: "5'5 ft",
    weight: "skinny queen",
    favoriteArtist: "Drake",
    favoriteSong: "Emotionless by Drake",
    favoriteSongUrl:
      "https://open.spotify.com/track/5Psnhdkyanjpgc2P8A5TSM?si=284c0c7979744068",
    favoriteSongEmbed:
      "https://open.spotify.com/embed/track/5Psnhdkyanjpgc2P8A5TSM?utm_source=generator",
    favoriteWord: "Fag",
    favoriteColor: "Black",
    playlistUrl: "https://spotify.link/r2FIv50t0Cb",
    imageUrl: "/assets/Shreya.png",
    description: "Nush's biggest hater",
    instagram: "https://instagram.com/reyakirpal",
    location: "Suva, Fiji",
    hobbies: ["sleeping (with ur mom)"],
    interests: ["sleeping (with ur mom)"],
    roles: ["ur mom's lover"],
    link: "/members/shreya",
    gif: "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExOXV1NmV6ZjB0am95ODgzazdvZ3F0M292ajI1ajE3cmo0Zzg2MXJ5dSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/7S6K3cc58aTzq/giphy.gif",
  },
  zeno: {
    name: "Zenovia Benazir",
    age: "15",
    dob: "04/03/08",
    height: "153cm",
    weight: "45kg",
    favoriteArtist: "J. Cole",
    favoriteSong: "One Love by Bob Marley☝🏾",
    favoriteSongUrl:
      "https://open.spotify.com/track/2BSwGHTh4kmckqXQfaCaAp?si=cb443ec526354b3b",
    favoriteSongEmbed:
      "https://open.spotify.com/embed/track/2BSwGHTh4kmckqXQfaCaAp?utm_source=generator",
    favoriteWord: "Caita",
    favoriteColor: "Green & Pink",
    playlistUrl: "https://spotify.link/1XFNBvktYCb",
    imageUrl: "/assets/Zeno.png",
    description: "in luv w my husband Shane",
    instagram: "https://instagram.com/realzenozoldyck",
    location: "Suva, Fiji",
    hobbies: ["Getting groomed"],
    interests: ["Older men", "Shane"],
    roles: ["Nothing"],
    link: "/members/zeno",
    gif: "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExMHg3ejk4aWN4M256dThkamZ4d2ZmODFpdXJtdTgwMXBwMHc0Z3hudiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/5S8LH2hkd5ONY7hyXJ/giphy.gif",
  },
};

export async function getMemberData(name) {
  return new Promise((resolve) => {
    const member = membersData[name];
    if (member) {
      resolve(member);
    } else {
      resolve(null);
    }
  });
}
