export const membersData = {
  aanush: {
    name: "Aanush Kumar",
    age: "15",
    dob: "20/09/07",
    height: "5'7",
    weight: "62kg",
    favoriteArtist: "Arctic Monkeys",
    favoriteSong: "Here With Me by D4vid",
    favoriteSongUrl:
      "https://open.spotify.com/track/5LrN7yUQAzvthd4QujgPFr?si=2878935ad4b244df",
    favoriteWord: "Jhattu",
    favoriteColor: "Prussian Blue",
    playlistUrl: "",
    imageUrl: "/assets/Aanush.jpg",
    description: "I Love Shreya.",
    instagram: "https://instagram.com/aanushkr",
    location: "Savusavu, Fiji",
    hobbies: ["Soccer", "Loving Shreya Kirpal"],
    interests: ["Shreya Kirpal"],
    roles: ["Shreya Luvr", "Shahaan's Mommy"],
    link: "/members/aanush",
    gif: "https://media.giphy.com/media/3o85xJohCZUc524lSU/giphy.gif",
  },
  shahaan: {
    name: "Shahaan Shameel",
    age: "16",
    dob: "16/08/07",
    height: "5'8ft",
    weight: "79kg",
    favoriteArtist: "Drake",
    favoriteSong: "505 by Arctic Monkeys",
    favoriteSongUrl: "",
    favoriteWord: "Propaganda",
    favoriteColor: "Blue",
    playlistUrl:
      "https://open.spotify.com/track/0BxE4FqsDD1Ot4YuBXwAPp?si=40eb02c7a8114823",
    imageUrl: "/assets/Shahaan.jpg",
    description: "Funny irl but not online.",
    instagram: "https://instagram.com/shqhqqn",
    location: "Suva, Fiji",
    hobbies: ["Gaming", "Harassment"],
    interests: [],
    roles: ["OVO"],
    link: "/members/Shahaan",
    gif: "https://cdn.discordapp.com/attachments/993789383868162098/1150395008659234846/giphy.gif",
  },
  nikhil: {
    name: "Nikhil Aryan Naiker",
    age: "17",
    height: "5'7ft",
    weight: "83kg",
    favoriteArtist: "The Weeknd",
    favoriteSong: "Wicked Games",
    favoriteSongUrl: "",
    favoriteWord: "XO",
    favoriteColor: "Black",
    playlistUrl:
      "https://open.spotify.com/playlist/6TrcN8ZyCUJCzORfmc0gZ0?si=6f8d4b515e6d4b84",
    imageUrl: "/assets/Nikhil.jpg",
    description: "I am vengeance",
    instagram: "https://instagram.com/fr3sh.budusy",
    location: "Suva, Fiji",
    hobbies: ["The Weeknd", "Brawlhalla", "Deadlifting"],
    interests: ["Powerlifitng", "Coding"],
    roles: ["XO", "Racist", "Batman", "She/Him"],
    link: "/members/nikhil",
    gif: "https://media.giphy.com/media/i7qODl4xzhcPPGf8Do/giphy.gif",
  },
  waji: {
    name: "Wajahat Munshi",
    age: "15",
    dob: "08/03/08",
    height: "175cm",
    weight: "74kg",
    favoriteArtist: "Baby Keem",
    favoriteSong: "16 by Baby Keem",
    favoriteSongUrl: "",
    favoriteWord: "starts with the letter n",
    favoriteColor: "Green",
    playlistUrl: "https://spotify.link/xRhavsetYCb",
    imageUrl: "/assets/Waji.jpg",
    description:
      "The funniest person in the world who is also very big and strong.",
    instagram: "https://instagram.com/wxjixz",
    location: "Suva, Fiji",
    hobbies: ["Lifting", "Gaming", "Crying"],
    interests: ["Science", "Math"],
    roles: ["Alpha Wolf"],
    link: "/members/waji",
    gif: "https://media.giphy.com/media/4QPaVH07ErzOk8jK9B/giphy.gif",
  },
  shane: {
    name: "Sharad Shane Jagrup ",
    age: "18",
    dob: "02/08/05",
    height: "5'7 ft",
    weight: "70kg",
    favoriteArtist: "The Neighborhood ",
    favoriteSong: "Secret Door by Arctic Monkeys",
    favoriteSongUrl: "",
    favoriteWord: "acha bhai ",
    favoriteColor: "Black",
    playlistUrl: "https://open.spotify.com/playlist/22UzQUqngjGBQnCS1INF27",
    imageUrl: "/assets/Shane.jpg",
    description: "I have a very low self esteem ",
    instagram: "https://instagram.com/xviishane",
    location: "Suva, Fiji",
    hobbies: ["Football"],
    interests: ["Going to the gym and take a 5 month break "],
    roles: ["Something "],
    link: "/members/shane",
    gif: "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExbmJzdGd1aGR0ZHp0Z2hyZDBkdGdyam5oZjBlN3FxeDk2dHY1ZGQzcSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/cOSbH8NoUFt9MXbuie/giphy.gif",
  },

  riddhi: {
    name: "Riddhi Bharat",
    age: "13",
    dob: "15/06/10",
    height: "4'10.5 ft",
    weight: "49kg",
    favoriteArtist: "Daniel Ceaser",
    favoriteSong: "Hold me down by Daniel Ceaser",
    favoriteSongUrl: "",
    favoriteWord: "Looooond",
    favoriteColor: "Lavender",
    playlistUrl:
      "https://open.spotify.com/playlist/7jwg7cbtufMVkOeyp9ZjzK?si=3a2kqUttQ8CBa6CLsTxiqA",
    imageUrl: "/assets/Riddhi.jpg",
    description:
      "I am the tallest person in nonchalant (im built like a dwarf) ",
    instagram: "https://instagram.com/rid2kool",
    location: "Suva, Fiji",
    hobbies: ["Reading", "Baking"],
    interests: ["Being a spectator in sports"],
    roles: ["Everything"],
    link: "/members/riddhi",
    gif: "https://media.giphy.com/media/Red9i0GN54sZW/giphy.gif",
  },
  xzya: {
    name: "Xzya Gagan",
    age: "18",
    dob: "19/05/05",
    height: "6ft",
    weight: "53kg",
    favoriteArtist: "Josh A",
    favoriteSong: "Heartbreaks by Josh A",
    favoriteSongUrl: "",
    favoriteWord: "Fuck",
    favoriteColor: "Black (it's a shade)",
    playlistUrl:
      "https://open.spotify.com/playlist/447RClBuLe7q1B0HhHx3HC?si=d708b56f450c4458",
    imageUrl: "/assets/Xzya.jpg",
    description:
      "I am a counselor for shane and pretty much chilling. I got a lovely gf n i hate school",
    instagram: "https://instagram.com/Priv_xzya",
    location: "Savusavu, Fiji",
    hobbies: ["Games", "Chill Sessions", "Rough ***"],
    interests: [
      "Preventing the universe from collapsing (checking up on the boys)",
    ],
    roles: ["God"],
    link: "/members/xzya",
    gif: "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExdjc2cjkyNjFmM2t4d2QzeHdhaDRyc3lidWo5NzdlNHA2OGVzZTdwNyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/gFPxNhzEWdFCCRAqf0/giphy.gif",
  },
  arav: {
    name: "Arav Deo",
    age: "14",
    dob: "20/10/08",
    height: "5'7 ft",
    weight: "55kg",
    favoriteArtist: "Leo Messi",
    favoriteSong: "Chaleya by Arjit Singh",
    favoriteSongUrl: "",
    favoriteWord: "Dovicai",
    favoriteColor: "Black",
    playlistUrl: "",
    imageUrl: "/assets/Arav.jpg",
    description: "Coming Soon...",
    instagram: "https://instagram.com/aravdeo108",
    location: "Suva, Fiji",
    hobbies: ["Games", "Soccer"],
    interests: ["Software", "Soccer"],
    roles: ["-"],
    link: "/members/arav",
    gif: "https://media.giphy.com/media/3osxYyPu7mA7ySNBgQ/giphy.gif",
  },
  ethan: {
    name: "Ethan Ram",
    age: "15",
    dob: "22/10/07",
    height: "5'3ft",
    weight: "50kg",
    favoriteArtist: "Clairo",
    favoriteSong: "Amoeba by Clairo",
    favoriteSongUrl: "",
    favoriteWord: "bro",
    favoriteColor: "Blue",
    playlistUrl: "",
    imageUrl: "/assets/Ethan.jpg",
    description: "best cm in the world irl and in fifa ",
    instagram: "https://instagram.com/3thqnexe",
    location: "California, US ",
    hobbies: ["Football", "Gaming"],
    interests: ["Journalism", "Photography"],
    roles: ["Comedic Relief"],
    link: "/members/ethan",
    gif: "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExMDF1bDM3NXlsbDJ2OTJoa3N2Z2szOTFqem9rMnFhb3o4MDIyNW5xeiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/xT1XH3TrY1zAEKgrQs/giphy.gif",
  },
  plavana: {
    name: "Plavana Singh",
    age: "15",
    dob: "26/11/07",
    height: "6'7 ft",
    weight: "69kg",
    favoriteArtist: "Taylor Swift",
    favoriteSong: "Style by Taylor Swift",
    favoriteSongUrl: "",
    favoriteWord: "F***",
    favoriteColor: "Yellowish Green",
    playlistUrl: "",
    imageUrl: "/assets/Plavana.jpg",
    description:
      "Stubborn, Short girl with brains, Pretty, Crybaby,Good fashion sense.",
    instagram: "https://instagram.com/",
    location: "Suva, Fiji",
    hobbies: ["None"],
    interests: ["I have none"],
    roles: ["None of ur business"],
    link: "/members/plavana",
    gif: "https://media.giphy.com/media/jO2B3Llymxny6BSObJ/giphy.gif",
  },
  josh: {
    name: "Josh Daniel",
    age: "15",
    dob: "10/01/08",
    height: "5'7 ft",
    weight: "67kg",
    favoriteArtist: "Drake",
    favoriteSong: "5am in Toronto by Drake",
    favoriteSongUrl: "",
    favoriteWord: "Nigeria",
    favoriteColor: "Purple",
    playlistUrl:
      "https://open.spotify.com/playlist/4hfMkBFUEDdz7jNjjGOSHx?si=4Bq6CrktQf6pUlivPrnoVw",
    imageUrl: "/assets/Josh.jpg",
    description: "Lazy dumb big forehead and cakobau",
    instagram: "https://instagram/beadybrag",
    location: "Lami, Fiji",
    hobbies: ["loser😔"],
    interests: ["Footy", "Anime"],
    roles: ["Member"],
    link: "/members/josh",
    gif: "https://media.giphy.com/media/1zgzISaYrnMAYRJJEr/giphy.gif",
  },
  dharav: {
    name: "Dharav Kapadia",
    age: "15",
    dob: "13/11/07",
    height: "6'2 ft",
    weight: "97kg",
    favoriteArtist: "Drake",
    favoriteSong: "Emotionless by Drake",
    favoriteSongUrl: "",
    favoriteWord: "Jhatu",
    favoriteColor: "Purple",
    playlistUrl: "https://spotify.link/1XFNBvktYCb",
    imageUrl: "/assets/Dharav.png",
    description: "My gf saw it first",
    instagram: "https://instagram.com/dhxravvv",
    location: "Suva, Fiji",
    hobbies: ["Talking to my gf"],
    interests: [
      "Listening to c.a.s while laying on the ground",
      "Watching the sunset",
    ],
    roles: ["Member"],
    link: "/members/dharav",
    gif: "https://media.giphy.com/media/xT4uQjxPma99QsihhK/giphy.gif",
  },
};

export async function getMemberData(name) {
  return new Promise((resolve) => {
    const member = membersData[name];
    if (member) {
      resolve(member);
    } else {
      resolve(null);
    }
  });
}
